Repository DriveFlow-CRM/DriveFlow-CRM-API, pull requests merged in 2025-05, with the labels that each got.

#11 C# Unit Tests
  DriveFlow.Tests/AddressNegativeTest.cs
  DriveFlow.Tests/AddressPositiveTest.cs
  DriveFlow.Tests/AuthoSchoolPositiveTest.cs
  DriveFlow.Tests/AutoSchoolNegativeTest.cs
  DriveFlow.Tests/CityNegativeTest.cs
  DriveFlow.Tests/CityPositiveTest.cs
  DriveFlow.Tests/CountyNegativeTest.cs
  DriveFlow.Tests/CountyPositiveTest.cs
  DriveFlow.Tests/DriveFlow.Tests.csproj
  DriveFlow.Tests/JwtGeneratorTokenPositiveTest.cs
  DriveFlow.Tests/LicenseNegativeTest.cs
  DriveFlow.Tests/LicensePositiveTest.cs
  DriveFlow.Tests/VehicleNegativeTest.cs
  DriveFlow.Tests/VehiclePositiveTest.cs
Labels: enhancement

#12 Implement File Details API and Fix Documentation Warnings
  DriveFlow-CRM-API/Controllers/SchoolAdminController.cs
  DriveFlow-CRM-API/Controllers/StudentController.cs
  DriveFlow-CRM-API/Controllers/StudentsController.cs
  DriveFlow-CRM-API/Json/AppJsonContext.cs
  DriveFlow-CRM-API/JwtAccessTokenGenerator.cs
  DriveFlow-CRM-API/Program.cs
Labels: good job coder!

#17 Invoice PDF Generation API Endpoint
  DriveFlow-CRM-API/Controllers/AccountingController.cs
  DriveFlow-CRM-API/DriveFlow-CRM-API.csproj
  DriveFlow-CRM-API/Program.cs
  DriveFlow.Tests/AccountingNegativeTest.cs
  DriveFlow.Tests/AccountingPositiveTest.cs
  README.md
Labels: enhancement

#24 Auto Schools Landing Page API
  DriveFlow-CRM-API/Controllers/AutoSchoolPageController.cs
  DriveFlow-CRM-API/Json/AppJsonContext.cs
  DriveFlow.Tests/AccountingNegativeTest.cs
  DriveFlow.Tests/AccountingPositiveTest.cs
Labels: good job coder!

#25 Instructor Controller and CRUD for Teaching Categories
  DriveFlow-CRM-API/Controllers/InstructorController.cs
  DriveFlow-CRM-API/Controllers/TeachingCategoryController.cs
  DriveFlow-CRM-API/Json/AppJsonContext.cs
Labels: enhancement

#35 File issue
  DriveFlow-CRM-API/Controllers/FileController.cs
  DriveFlow-CRM-API/Controllers/RequestController.cs
  DriveFlow-CRM-API/Controllers/SchoolAdminController.cs
Labels: good job coder!

#38 Instructor–TeachingCategory Management CRUD
  DriveFlow-CRM-API/Controllers/ApplicationUserTeachingCategoryController.cs
  DriveFlow-CRM-API/Json/AppJsonContext.cs
Labels: enhancement, good job coder!

#41 handled appointments
  DriveFlow-CRM-API/Controllers/FileController.cs
  DriveFlow-CRM-API/Controllers/InstructorAvailabilityController.cs
  DriveFlow-CRM-API/Controllers/StudentController.cs
Labels: good job coder!
